#!/usr/bin/env python3
"""Evaluate a longer 500-bot cold+warm soak for the measured release profile."""

from __future__ import annotations

import argparse
import datetime as dt
import pathlib
import sys

import evaluate_production_release


ROOT = pathlib.Path(__file__).resolve().parents[1]


def bool_text(value: bool) -> str:
    return str(value).lower()


def select_summary(requested: str, profile_name: str) -> evaluate_production_release.SummaryVerdict:
    if requested in {"skip", "skipped"}:
        return evaluate_production_release.SummaryVerdict(
            pathlib.Path("skipped"),
            profile_name,
            False,
            [f"{profile_name} summary skipped by soak wrapper"],
            {},
            {"skipped": "true"},
        )

    path = evaluate_production_release.resolve_path(requested)
    if not path.is_file():
        raise SystemExit(f"Missing {profile_name} summary: {path}")
    return evaluate_production_release.evaluate_summary(path, profile_name)


def is_skipped(verdict: evaluate_production_release.SummaryVerdict) -> bool:
    return verdict.metadata.get("skipped") == "true"


def int_value(values: dict[str, str], key: str, failures: list[str], label: str) -> int | None:
    raw = values.get(key)
    if raw is None:
        failures.append(f"{label}: {key} is missing")
        return None
    try:
        return int(float(raw))
    except ValueError:
        failures.append(f"{label}: {key}={raw} is not numeric")
        return None


def require_int_at_least(
    *,
    values: dict[str, str],
    key: str,
    minimum: int,
    failures: list[str],
    label: str,
) -> None:
    observed = int_value(values, key, failures, label)
    if observed is not None and observed < minimum:
        failures.append(f"{label}: {key}={observed} < required {minimum}")


def add_soak_summary_lines(
    lines: list[str],
    prefix: str,
    verdict: evaluate_production_release.SummaryVerdict,
    extra_failures: list[str],
) -> None:
    evaluate_production_release.add_summary_lines(lines, prefix, verdict)
    selected_keys = [
        "block_ramp_seconds",
        "global_action_start_after_ms",
        "block_action_interval_ms",
        "bot_block_actions_per_sec_max",
        "compat_probe_block_places_max",
        "compat_probe_block_breaks_max",
        "compat_probe_block_evidence_accepted",
        "compat_probe_block_metrics_loadbot_direct_evidence",
        "compat_probe_block_event_loadbot_places_max",
        "compat_probe_block_event_loadbot_breaks_max",
        *evaluate_production_release.SEND_PRESSURE_KEYS,
        "process_cpu_max",
        "process_rss_mib_max",
    ]
    for key in selected_keys:
        value = verdict.values.get(key)
        if value is not None:
            lines.append(f"{prefix}_{key}={value}")
    for failure in extra_failures:
        lines.append(f"{prefix}_soak_failure={failure}")


def evaluate_soak_requirements(
    verdict: evaluate_production_release.SummaryVerdict,
    *,
    label: str,
    min_load_window_metrics_samples: int,
    min_block_place_packets: int,
    min_block_dig_packets: int,
) -> list[str]:
    failures: list[str] = []
    require_int_at_least(
        values=verdict.values,
        key="load_window_metrics_samples",
        minimum=min_load_window_metrics_samples,
        failures=failures,
        label=label,
    )
    require_int_at_least(
        values=verdict.values,
        key="bot_block_place_packets_max",
        minimum=min_block_place_packets,
        failures=failures,
        label=label,
    )
    require_int_at_least(
        values=verdict.values,
        key="bot_block_dig_packets_max",
        minimum=min_block_dig_packets,
        failures=failures,
        label=label,
    )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cold-summary", required=True, help="production-500 cold/fresh summary path")
    parser.add_argument("--warm-summary", required=True, help="production-500-warm saved-world summary path")
    parser.add_argument(
        "--artifact-hashes",
        default="reports/artifact-hashes.txt",
        help="sha256sum-style artifact hash manifest",
    )
    parser.add_argument(
        "--artifacts-json",
        default="reports/artifacts.json",
        help="artifact metadata JSON generated by update_artifact_reports.py",
    )
    parser.add_argument(
        "--report",
        default="reports/production-500-soak-gate.txt",
        help="output soak gate report path",
    )
    parser.add_argument(
        "--require-current-artifacts",
        action="store_true",
        help="require load summaries to include hashes matching reports/artifacts.json",
    )
    parser.add_argument(
        "--min-load-window-metrics-samples",
        type=int,
        default=300,
        help="Minimum load-window metrics samples per cold/warm run.",
    )
    parser.add_argument(
        "--min-block-place-packets",
        type=int,
        default=120_000,
        help="Minimum block place packets per cold/warm run.",
    )
    parser.add_argument(
        "--min-block-dig-packets",
        type=int,
        default=120_000,
        help="Minimum block dig packets per cold/warm run.",
    )
    args = parser.parse_args()

    if args.min_load_window_metrics_samples < 1:
        raise SystemExit("--min-load-window-metrics-samples must be >= 1")
    if args.min_block_place_packets < 1:
        raise SystemExit("--min-block-place-packets must be >= 1")
    if args.min_block_dig_packets < 1:
        raise SystemExit("--min-block-dig-packets must be >= 1")

    cold = select_summary(args.cold_summary, "production-500")
    warm = select_summary(args.warm_summary, "production-500-warm")

    artifact_hashes = evaluate_production_release.resolve_path(args.artifact_hashes)
    artifacts_json = evaluate_production_release.resolve_path(args.artifacts_json)
    report_path = evaluate_production_release.resolve_path(args.report)

    failures: list[str] = []
    if is_skipped(cold):
        failures.append("cold production-500 summary skipped")
    elif not cold.passed:
        failures.append("cold production-500 release gate failed")
    if is_skipped(warm):
        failures.append("warm production-500-warm summary skipped")
    elif not warm.passed:
        failures.append("warm production-500-warm release gate failed")

    if not artifact_hashes.is_file():
        hash_passed = False
        hash_count = 0
        hash_failures = [f"{artifact_hashes}: missing artifact hash manifest"]
    else:
        hash_passed, hash_count, hash_failures = evaluate_production_release.verify_artifact_hashes(
            artifact_hashes
        )
    if not hash_passed:
        failures.append("artifact hash verification failed")
    failures.extend(hash_failures)

    artifacts, artifact_json_failures = evaluate_production_release.load_artifacts(artifacts_json)
    if artifact_json_failures:
        failures.append("artifact metadata verification failed")
        failures.extend(artifact_json_failures)
    if args.require_current_artifacts:
        if artifacts:
            current_artifact_failures = []
            if not is_skipped(cold):
                current_artifact_failures.extend(
                    evaluate_production_release.check_current_artifact_binding(cold, artifacts)
                )
            if not is_skipped(warm):
                current_artifact_failures.extend(
                    evaluate_production_release.check_current_artifact_binding(warm, artifacts)
                )
        else:
            current_artifact_failures = [
                "current artifact binding requested but artifacts JSON is unavailable"
            ]
        if current_artifact_failures:
            failures.append("load summaries are not bound to current artifacts")
            failures.extend(current_artifact_failures)

    cold_soak_failures = []
    if not is_skipped(cold):
        cold_soak_failures = evaluate_soak_requirements(
            cold,
            label="cold",
            min_load_window_metrics_samples=args.min_load_window_metrics_samples,
            min_block_place_packets=args.min_block_place_packets,
            min_block_dig_packets=args.min_block_dig_packets,
        )
    warm_soak_failures = []
    if not is_skipped(warm):
        warm_soak_failures = evaluate_soak_requirements(
            warm,
            label="warm",
            min_load_window_metrics_samples=args.min_load_window_metrics_samples,
            min_block_place_packets=args.min_block_place_packets,
            min_block_dig_packets=args.min_block_dig_packets,
        )
    if cold_soak_failures:
        failures.append("cold soak requirements failed")
        failures.extend(cold_soak_failures)
    if warm_soak_failures:
        failures.append("warm soak requirements failed")
        failures.extend(warm_soak_failures)

    optimized = artifacts.get("optimized", {}) if isinstance(artifacts, dict) else {}
    runtime = artifacts.get("optimized_runtime", {}) if isinstance(artifacts, dict) else {}
    ready = not failures

    lines = [
        "soak_profile=production-500-soak-release",
        f"generated_at_utc={dt.datetime.now(dt.timezone.utc).isoformat()}",
        "claim_text=500-bots-production-ready-soak-for-measured-32-32-creative-block-profile",
        "claim_scope=cold-fresh-and-warm-source-500-bots-32-view-32-simulation-creative-block-soak",
        "claim_limits=not-full-paper-runtime-rust-rewrite;not-unbounded-plugin-compatibility;not-unmeasured-real-player-gameplay",
        f"production_ready_soak_claim_eligible={bool_text(ready)}",
        f"soak_gate_pass={bool_text(ready)}",
        f"failure_count={len(failures)}",
        f"base_cold_gate_pass={bool_text(cold.passed)}",
        f"base_warm_gate_pass={bool_text(warm.passed)}",
        f"artifact_hash_manifest={artifact_hashes}",
        f"artifact_hashes_pass={bool_text(hash_passed)}",
        f"artifact_hash_count={hash_count}",
        f"artifacts_json={artifacts_json}",
        f"requires_current_artifacts={bool_text(args.require_current_artifacts)}",
        f"required_load_window_metrics_samples_min={args.min_load_window_metrics_samples}",
        f"required_block_place_packets_min={args.min_block_place_packets}",
        f"required_block_dig_packets_min={args.min_block_dig_packets}",
    ]
    if isinstance(optimized, dict):
        if "path" in optimized:
            lines.append(f"optimized_artifact_path={optimized['path']}")
        if "sha256" in optimized:
            lines.append(f"optimized_artifact_sha256={optimized['sha256']}")
    if isinstance(runtime, dict):
        run_sh = runtime.get("run_sh", {})
        native_library = runtime.get("native_library", {})
        chunk_encode_native_library = runtime.get("chunk_encode_native_library", {})
        if isinstance(run_sh, dict) and "path" in run_sh:
            lines.append(f"optimized_runtime_run_sh={run_sh['path']}")
        if isinstance(native_library, dict):
            if "path" in native_library:
                lines.append(f"optimized_runtime_native_library={native_library['path']}")
            if "sha256" in native_library:
                lines.append(f"optimized_runtime_native_library_sha256={native_library['sha256']}")
        if isinstance(chunk_encode_native_library, dict):
            if "path" in chunk_encode_native_library:
                lines.append(f"optimized_runtime_chunk_encode_native_library={chunk_encode_native_library['path']}")
            if "sha256" in chunk_encode_native_library:
                lines.append(f"optimized_runtime_chunk_encode_native_library_sha256={chunk_encode_native_library['sha256']}")

    add_soak_summary_lines(lines, "cold", cold, cold_soak_failures)
    add_soak_summary_lines(lines, "warm", warm, warm_soak_failures)
    for failure in failures:
        lines.append(f"failure={failure}")

    report = "\n".join(lines) + "\n"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    print(report, end="")
    return 0 if ready else 1


if __name__ == "__main__":
    sys.exit(main())
