#!/usr/bin/env python3
"""Generate the runtime-name alias table used by the transform engine.

Why this exists
---------------
Rule method names are written in Mojang (official) names. Paper 1.20.5+ and
NeoForge run official names at runtime, so those kernels match by name. Forge
1.20.1 (and anything else that runs Searge names) does **not**: the very same
method is `m_5705_(Ljava/util/function/BooleanSupplier;)V` at runtime, so a rule
whose class matched but whose method name did not produced an empty plan and the
whole platform surface silently stayed unwired.

The engine resolves such rules in three namespace-agnostic ways:
  1. exact official name (Paper 1.20.5+/NeoForge),
  2. the alias list generated here (Searge names), and
  3. a descriptor-unique fallback for platform rules (`Rule::platform`).

Usage
-----
    python3 scripts/gen_srg_aliases.py <srg_to_official.tsrg> > \
        runtime/src/platform/runtime_names.rs

The output replaces the generated block inside that file (keep the module docs
at the top). The TSRG2 shape consumed here is ForgeGradle's
`srg_to_official_<mc>.tsrg`:

    tsrg2 left right
    <srg/class> <official/class>
    \t<srg/member> <descriptor> <official/member>
    \t\t<param-index> <srg> <official>      (parameter rows, ignored)
"""
import sys

# (class internal name, official method name, descriptor or None for "every
# overload") — exactly the targets of the default rule tables.
TARGETS = [
    ("net/minecraft/server/MinecraftServer", "tickServer",
     "(Ljava/util/function/BooleanSupplier;)V"),
    ("net/minecraft/server/MinecraftServer", "saveAllChunks", "(ZZZ)Z"),
    ("net/minecraft/server/MinecraftServer", "saveAllChunks", "(ZZZZ)Z"),
    ("net/minecraft/server/MinecraftServer", "autoSave", "()V"),
    ("net/minecraft/server/level/ServerLevel", "tick",
     "(Ljava/util/function/BooleanSupplier;)V"),
    ("net/minecraft/world/ticks/LevelTicks", "tick", None),
    ("net/minecraft/network/PacketDecoder", "decode",
     "(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V"),
    ("net/minecraft/network/PacketEncoder", "encode",
     "(Lio/netty/channel/ChannelHandlerContext;Lnet/minecraft/network/protocol/Packet;Lio/netty/buffer/ByteBuf;)V"),
    ("net/minecraft/server/network/ServerHandshakePacketListenerImpl", "handleIntention",
     "(Lnet/minecraft/network/protocol/handshake/ClientIntentionPacket;)V"),
    ("net/minecraft/network/Connection", "setupInboundProtocol",
     "(Lnet/minecraft/network/ProtocolInfo;Lnet/minecraft/network/PacketListener;)V"),
    ("net/minecraft/network/Connection", "channelInactive",
     "(Lio/netty/channel/ChannelHandlerContext;)V"),
    ("net/minecraft/network/Connection", "getPacketListener",
     "()Lnet/minecraft/network/PacketListener;"),
]


def parse(tsrg_path):
    """{(class, official_name, descriptor): srg_name}. Minecraft class names are
    identical on both sides; member rows carry the mapping."""
    out = {}
    current = None
    with open(tsrg_path, encoding="utf-8") as fh:
        for line in fh:
            if not line.strip() or line.startswith("tsrg2"):
                continue
            if not line.startswith("\t"):
                parts = line.split()
                current = parts[1] if len(parts) > 1 else parts[0]
                continue
            if line.startswith("\t\t"):  # parameter row
                continue
            parts = line.strip().split()
            if len(parts) < 3:
                continue
            srg, desc, official = parts[0], parts[1], parts[2]
            out[(current, official, desc)] = srg
    return out


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    table = parse(sys.argv[1])
    rows, absent = [], []
    for cls, official, desc in TARGETS:
        hits = sorted(
            (d, srg) for (c, o, d), srg in table.items()
            if c == cls and o == official and (desc is None or d == desc)
        )
        if not hits:
            absent.append((cls, official, desc))
            continue
        for d, srg in hits:
            rows.append((cls, official, d, srg))
    print("// GENERATED by scripts/gen_srg_aliases.py — do not edit by hand.")
    print("//")
    print("// Forge 1.20.1 runtime (Searge) names for the methods the default rule")
    print("// tables target. Source: ForgeGradle mcp_config srg_to_official_1.20.1.tsrg.")
    print("pub const SRG_ALIASES: &[(&str, &str, &str, &str)] = &[")
    for cls, official, desc, srg in rows:
        print(f'    ("{cls}", "{official}", "{desc}", "{srg}"),')
    print("];")
    for cls, official, desc in absent:
        # Not a problem: the rule targets a method that does not exist in this
        # Minecraft version (those rules resolve on the versions that have it).
        print(f"// not present in this mapping: {cls}.{official} {desc}", file=sys.stderr)
    print(f"// {len(rows)} alias row(s), {len(absent)} absent from this mapping", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
