#!/usr/bin/env python3
"""Generate v2/modules/crussty/src/jni_table.rs from Crussty CE native exports.

Parses `pub extern "system" fn Java_<fqcn>_<method>(...)` signatures in the
paper-native-jni / paper-native-chunk-encode-jni crates and emits:
  - MAIN_JNI_TABLE / CHUNK_JNI_TABLE: (class internal name, method, JNI sig, symbol)
  - MAIN_BRIDGE_CLASSES / CHUNK_BRIDGE_CLASSES: unique class names per library

JNI symbol -> method signature rule: the VM derives the native method
signature from the JNI function name; our bridge classes declare
`public static native <ret> <method>(<params>)` exactly as emitted here.
"""
import re
import sys

ROOT = "/home/btw/crussty-dist/crussty/native"
OUT = "/home/btw/crussty-dist/v2/modules/crussty/src/jni_table.rs"

TYPE_MAP = {
    "jboolean": "Z", "jbyte": "B", "jchar": "C", "jshort": "S", "jint": "I",
    "jlong": "J", "jfloat": "F", "jdouble": "D", "jsize": "I", "void": "V",
    "jbooleanArray": "[Z", "jbyteArray": "[B", "jcharArray": "[C",
    "jshortArray": "[S", "jintArray": "[I", "jlongArray": "[J",
    "jfloatArray": "[F", "jdoubleArray": "[D",
    "jobjectArray": "[Ljava/lang/Object;",
    "jstring": "Ljava/lang/String;", "jobject": "Ljava/lang/Object;",
    "jclass": "Ljava/lang/Class;",
    "JString": "Ljava/lang/String;",
}

# env/class params every JNI method has; never part of the Java signature
SKIP = {"JNIEnv", "JClass", "JavaVM"}


def clean(t):
    t = t.strip()
    t = t.replace("jni::sys::", "").replace("jni::objects::", "").replace("jni::", "")
    return t


def parse_file(path, out):
    src = open(path).read()
    for m in re.finditer(r'pub extern "system" fn (Java_[A-Za-z0-9_]+)\(', src):
        start = m.end()
        depth = 1
        i = start
        while depth:
            if src[i] == "(":
                depth += 1
            elif src[i] == ")":
                depth -= 1
            i += 1
        body = src[start : i - 1]
        rest = src[i:]
        rm = re.match(r"\s*->\s*([^\s{]+)", rest)
        ret = clean(rm.group(1)) if rm else "void"

        params = []
        cur = ""
        depth = 0
        for ch in body:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                params.append(cur)
                cur = ""
            else:
                cur += ch
        if cur.strip():
            params.append(cur)

        jni = []
        for p in params:
            p = p.strip()
            if not p:
                continue
            ty = clean(p.split(":")[-1])
            if ty in SKIP:
                continue
            if ty not in TYPE_MAP:
                sys.exit(f"UNKNOWN PARAM TYPE {ty!r} in {m.group(1)} ({path})")
            jni.append(TYPE_MAP[ty])
        if ret not in TYPE_MAP:
            sys.exit(f"UNKNOWN RETURN TYPE {ret!r} in {m.group(1)} ({path})")

        symbol = m.group(1)
        parts = symbol[len("Java_") :].split("_")
        method = parts[-1]
        cls = "/".join(parts[:-1])
        sig = "(" + "".join(jni) + ")" + TYPE_MAP[ret]
        out.append((cls, method, sig, symbol))


def emit(out, statics):
    lines = []
    lines.append("// Generated by scripts/gen_crussty_table.py -- DO NOT EDIT.")
    lines.append("// JNI bridge table for the Crussty CE native surface (283 natives).")
    lines.append("pub struct JniEntry {")
    lines.append("    pub class: &'static str,")
    lines.append("    pub method: &'static str,")
    lines.append("    pub sig: &'static str,")
    lines.append("    pub symbol: &'static str,")
    lines.append("}")
    lines.append("")
    for name, entries in statics:
        lines.append(f"#[rustfmt::skip]")
        lines.append(f"pub static {name}: &[JniEntry] = &[")
        for cls, method, sig, symbol in entries:
            lines.append(
                f'    JniEntry {{ class: "{cls}", method: "{method}", '
                f'sig: "{sig}", symbol: "{symbol}" }},'
            )
        lines.append("];")
        lines.append("")
        classes = sorted({c for c, _, _, _ in entries})
        clsname = name.replace("_JNI_TABLE", "_BRIDGE_CLASSES")
        lines.append(f"pub static {clsname}: &[&str] = &[")
        for c in classes:
            lines.append(f'    "{c}",')
        lines.append("];")
        lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))


main = []
chunk = []
parse_file(f"{ROOT}/paper-native-jni/src/lib.rs", main)
parse_file(f"{ROOT}/paper-native-chunk-encode-jni/src/lib.rs", chunk)

seen = set()
for c, m, s, sym in main + chunk:
    if sym in seen:
        sys.exit(f"DUPLICATE EXPORT {sym}")
    seen.add(sym)

print(f"main: {len(main)} exports, {len({c for c,_,_,_ in main})} classes")
print(f"chunk: {len(chunk)} exports, {len({c for c,_,_,_ in chunk})} classes")
emit(OUT, [("MAIN_JNI_TABLE", main), ("CHUNK_JNI_TABLE", chunk)])
print(f"wrote {OUT}")
