#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BOT_COUNT="${BOT_COUNT:-50}"
DURATION_SECONDS="${DURATION_SECONDS:-180}"
VIEW_DISTANCE="${VIEW_DISTANCE:-16}"
SIMULATION_DISTANCE="${SIMULATION_DISTANCE:-16}"
LOAD_TEST_LABEL="${LOAD_TEST_LABEL:-stress-mixed-${BOT_COUNT}}"
LOAD_TEST_SCENARIO="${LOAD_TEST_SCENARIO:-mixed}"
LOAD_TEST_GAMEMODE="${LOAD_TEST_GAMEMODE:-survival}"
LOAD_TEST_STRESS_CORPUS="${LOAD_TEST_STRESS_CORPUS:-true}"
LOAD_TEST_MOB_STORM_COUNT="${LOAD_TEST_MOB_STORM_COUNT:-150}"
LOAD_TEST_MOB_STORM_ENTITY="${LOAD_TEST_MOB_STORM_ENTITY:-zombie}"
LOAD_TEST_MOB_STORM_CENTER_X="${LOAD_TEST_MOB_STORM_CENTER_X:-0}"
LOAD_TEST_MOB_STORM_CENTER_Z="${LOAD_TEST_MOB_STORM_CENTER_Z:-0}"
LOAD_TEST_MOB_STORM_Y="${LOAD_TEST_MOB_STORM_Y:-surface}"
LOAD_TEST_MOB_STORM_SPACING="${LOAD_TEST_MOB_STORM_SPACING:-2}"
LOAD_TEST_MOB_STORM_COLUMNS="${LOAD_TEST_MOB_STORM_COLUMNS:-15}"
LOAD_TEST_GATE_PROFILE="${LOAD_TEST_GATE_PROFILE:-stress-mixed}"
LOAD_TEST_ALLOW_BUSY_HOST="${LOAD_TEST_ALLOW_BUSY_HOST:-false}"

if [[ "${PRECOMPUTE_STRESS_CORPUS:-false}" == "true" ]]; then
  MC_EULA_AGREE=true PRECOMPUTE_STRESS_CORPUS=true ./scripts/precompute_plugin_remaps.sh
fi

set +e
MC_EULA_AGREE=true \
BOT_COUNT="$BOT_COUNT" \
DURATION_SECONDS="$DURATION_SECONDS" \
VIEW_DISTANCE="$VIEW_DISTANCE" \
SIMULATION_DISTANCE="$SIMULATION_DISTANCE" \
LOAD_TEST_LABEL="$LOAD_TEST_LABEL" \
LOAD_TEST_SCENARIO="$LOAD_TEST_SCENARIO" \
LOAD_TEST_GAMEMODE="$LOAD_TEST_GAMEMODE" \
LOAD_TEST_STRESS_CORPUS="$LOAD_TEST_STRESS_CORPUS" \
LOAD_TEST_MOB_STORM_COUNT="$LOAD_TEST_MOB_STORM_COUNT" \
LOAD_TEST_MOB_STORM_ENTITY="$LOAD_TEST_MOB_STORM_ENTITY" \
LOAD_TEST_MOB_STORM_CENTER_X="$LOAD_TEST_MOB_STORM_CENTER_X" \
LOAD_TEST_MOB_STORM_CENTER_Z="$LOAD_TEST_MOB_STORM_CENTER_Z" \
LOAD_TEST_MOB_STORM_Y="$LOAD_TEST_MOB_STORM_Y" \
LOAD_TEST_MOB_STORM_SPACING="$LOAD_TEST_MOB_STORM_SPACING" \
LOAD_TEST_MOB_STORM_COLUMNS="$LOAD_TEST_MOB_STORM_COLUMNS" \
LOAD_TEST_GATE_PROFILE="$LOAD_TEST_GATE_PROFILE" \
LOAD_TEST_ALLOW_BUSY_HOST="$LOAD_TEST_ALLOW_BUSY_HOST" \
./scripts/run_load_test.sh
load_status=$?
set -e

gate_report="$ROOT/reports/stress-mixed-load-gate.txt"
summary_path="$ROOT/reports/load-${LOAD_TEST_LABEL}-summary.txt"
set +e
python3 "$ROOT/scripts/evaluate_load_gate.py" \
  --profile stress-mixed \
  --report "$gate_report" \
  "$summary_path"
gate_status=$?
set -e

if [[ -f "$gate_report" ]]; then
  cat "$gate_report"
fi

if (( load_status != 0 )); then
  exit "$load_status"
fi
exit "$gate_status"
