#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BOT_COUNT="${BOT_COUNT:-50}"
DURATION_SECONDS="${DURATION_SECONDS:-360}"
VIEW_DISTANCE="${VIEW_DISTANCE:-16}"
SIMULATION_DISTANCE="${SIMULATION_DISTANCE:-16}"
BOT_ALTITUDE="${BOT_ALTITUDE:-160}"
LOAD_TEST_LABEL="${LOAD_TEST_LABEL:-stress-mixed-gameplay-${BOT_COUNT}}"
LOAD_TEST_SCENARIO="${LOAD_TEST_SCENARIO:-mixed-gameplay}"
LOAD_TEST_GAMEMODE="${LOAD_TEST_GAMEMODE:-creative}"
LOAD_TEST_STRESS_CORPUS="${LOAD_TEST_STRESS_CORPUS:-true}"
LOAD_TEST_MOB_STORM_COUNT="${LOAD_TEST_MOB_STORM_COUNT:-150}"
LOAD_TEST_MOB_STORM_ENTITY="${LOAD_TEST_MOB_STORM_ENTITY:-zombie}"
LOAD_TEST_MOB_STORM_CENTER_X="${LOAD_TEST_MOB_STORM_CENTER_X:-0}"
LOAD_TEST_MOB_STORM_CENTER_Z="${LOAD_TEST_MOB_STORM_CENTER_Z:-0}"
LOAD_TEST_MOB_STORM_Y="${LOAD_TEST_MOB_STORM_Y:-$BOT_ALTITUDE}"
LOAD_TEST_MOB_STORM_SPACING="${LOAD_TEST_MOB_STORM_SPACING:-2}"
LOAD_TEST_MOB_STORM_COLUMNS="${LOAD_TEST_MOB_STORM_COLUMNS:-15}"
LOAD_TEST_ARENA_PRELOAD_RADIUS_CHUNKS="${LOAD_TEST_ARENA_PRELOAD_RADIUS_CHUNKS:-$VIEW_DISTANCE}"
LOAD_TEST_ARENA_PRELOAD_MAX_IN_FLIGHT="${LOAD_TEST_ARENA_PRELOAD_MAX_IN_FLIGHT:-${PAPER_CHUNK_WORKER_THREADS:-12}}"
BOT_SPEED="${BOT_SPEED:-6}"
BOT_MOVE_INTERVAL_MS="${BOT_MOVE_INTERVAL_MS:-250}"
BOT_MIXED_ACTION_INTERVAL_MS="${BOT_MIXED_ACTION_INTERVAL_MS:-200}"
BOT_MIXED_COMMAND_INTERVAL_MS="${BOT_MIXED_COMMAND_INTERVAL_MS:-10000}"
BOT_MIXED_USE_ENTITY_ATTACKS="${BOT_MIXED_USE_ENTITY_ATTACKS:-false}"
BOT_ACTION_START_MODE="${BOT_ACTION_START_MODE:-all-ready}"
BOT_ACTION_READY_SETTLE_MS="${BOT_ACTION_READY_SETTLE_MS:-15000}"
BOT_ACTION_READY_MIN_COUNT="${BOT_ACTION_READY_MIN_COUNT:-$BOT_COUNT}"
BOT_ACTION_READY_MIN_FRACTION="${BOT_ACTION_READY_MIN_FRACTION:-1}"
BOT_CHECK_TIMEOUT_INTERVAL_MS="${BOT_CHECK_TIMEOUT_INTERVAL_MS:-180000}"
BOT_MIN_RUN_AFTER_ACTION_OPEN_MS="${BOT_MIN_RUN_AFTER_ACTION_OPEN_MS:-180000}"
BOT_MAX_DURATION_MS="${BOT_MAX_DURATION_MS:-$(( DURATION_SECONDS * 1000 + BOT_MIN_RUN_AFTER_ACTION_OPEN_MS ))}"
LOAD_TEST_GATE_PROFILE="${LOAD_TEST_GATE_PROFILE:-stress-mixed-gameplay}"
LOAD_TEST_ALLOW_BUSY_HOST="${LOAD_TEST_ALLOW_BUSY_HOST:-false}"
LOAD_TEST_SERVER_READY_TIMEOUT_SECONDS="${LOAD_TEST_SERVER_READY_TIMEOUT_SECONDS:-900}"

set +e
MC_EULA_AGREE=true \
BOT_COUNT="$BOT_COUNT" \
DURATION_SECONDS="$DURATION_SECONDS" \
VIEW_DISTANCE="$VIEW_DISTANCE" \
SIMULATION_DISTANCE="$SIMULATION_DISTANCE" \
BOT_ALTITUDE="$BOT_ALTITUDE" \
BOT_SPEED="$BOT_SPEED" \
BOT_MOVE_INTERVAL_MS="$BOT_MOVE_INTERVAL_MS" \
BOT_MIXED_ACTION_INTERVAL_MS="$BOT_MIXED_ACTION_INTERVAL_MS" \
BOT_MIXED_COMMAND_INTERVAL_MS="$BOT_MIXED_COMMAND_INTERVAL_MS" \
BOT_MIXED_USE_ENTITY_ATTACKS="$BOT_MIXED_USE_ENTITY_ATTACKS" \
BOT_ACTION_START_MODE="$BOT_ACTION_START_MODE" \
BOT_ACTION_READY_SETTLE_MS="$BOT_ACTION_READY_SETTLE_MS" \
BOT_ACTION_READY_MIN_COUNT="$BOT_ACTION_READY_MIN_COUNT" \
BOT_ACTION_READY_MIN_FRACTION="$BOT_ACTION_READY_MIN_FRACTION" \
BOT_CHECK_TIMEOUT_INTERVAL_MS="$BOT_CHECK_TIMEOUT_INTERVAL_MS" \
BOT_MIN_RUN_AFTER_ACTION_OPEN_MS="$BOT_MIN_RUN_AFTER_ACTION_OPEN_MS" \
BOT_MAX_DURATION_MS="$BOT_MAX_DURATION_MS" \
LOAD_TEST_LABEL="$LOAD_TEST_LABEL" \
LOAD_TEST_SCENARIO="$LOAD_TEST_SCENARIO" \
LOAD_TEST_GAMEMODE="$LOAD_TEST_GAMEMODE" \
LOAD_TEST_STRESS_CORPUS="$LOAD_TEST_STRESS_CORPUS" \
LOAD_TEST_MOB_STORM_COUNT="$LOAD_TEST_MOB_STORM_COUNT" \
LOAD_TEST_MOB_STORM_ENTITY="$LOAD_TEST_MOB_STORM_ENTITY" \
LOAD_TEST_MOB_STORM_CENTER_X="$LOAD_TEST_MOB_STORM_CENTER_X" \
LOAD_TEST_MOB_STORM_CENTER_Z="$LOAD_TEST_MOB_STORM_CENTER_Z" \
LOAD_TEST_MOB_STORM_Y="$LOAD_TEST_MOB_STORM_Y" \
LOAD_TEST_MOB_STORM_SPACING="$LOAD_TEST_MOB_STORM_SPACING" \
LOAD_TEST_MOB_STORM_COLUMNS="$LOAD_TEST_MOB_STORM_COLUMNS" \
LOAD_TEST_ARENA_PRELOAD_RADIUS_CHUNKS="$LOAD_TEST_ARENA_PRELOAD_RADIUS_CHUNKS" \
LOAD_TEST_ARENA_PRELOAD_MAX_IN_FLIGHT="$LOAD_TEST_ARENA_PRELOAD_MAX_IN_FLIGHT" \
LOAD_TEST_GATE_PROFILE="$LOAD_TEST_GATE_PROFILE" \
LOAD_TEST_ALLOW_BUSY_HOST="$LOAD_TEST_ALLOW_BUSY_HOST" \
LOAD_TEST_SERVER_READY_TIMEOUT_SECONDS="$LOAD_TEST_SERVER_READY_TIMEOUT_SECONDS" \
"$ROOT/scripts/run_load_test.sh"
load_status=$?
set -e

gate_report="$ROOT/reports/load-${LOAD_TEST_LABEL}-gate.txt"
summary_path="$ROOT/reports/load-${LOAD_TEST_LABEL}-summary.txt"

if [[ ! -f "$gate_report" && -f "$summary_path" ]]; then
  set +e
  python3 "$ROOT/scripts/evaluate_load_gate.py" \
    --profile "$LOAD_TEST_GATE_PROFILE" \
    --report "$gate_report" \
    "$summary_path"
  gate_status=$?
  set -e
else
  gate_status=0
fi

if [[ -f "$gate_report" ]]; then
  cat "$gate_report"
fi

if (( load_status != 0 )); then
  exit "$load_status"
fi
exit "$gate_status"
