//! JNI hook classes required by the platform transform rules.
//!
//! The transform engine injects `invokestatic` probes (`()V`) into kernel
//! classes — `dev.crussty.hooks.SchedulerHooks`, `dev.crusty.hooks.StorageHooks`,
//! `dev.crussty.hooks.NetHooks`, `dev.crussty.hooks.TickHook`. The JVM
//! resolves those classes lazily at first execution of the patched method,
//! so the platform must ship them. We do: the `.class` files are committed
//! under `runtime/build/hooks/` (regenerated by `scripts/build-helpers.sh`
//! from `runtime/hook-src/`), embedded via `include_bytes!`, defined into
//! the system class loader at agent start, and their natives registered
//! (`RegisterNatives`) against the runtime's own code pointers — no symbol
//! exports required.
//!
//! Failure is not fatal to the agent itself, but it is logged loudly:
//! patched kernel classes will throw `NoClassDefFoundError` on first
//! execution of a transformed method.

use crate::platform::{scheduler, storage};
use jni::objects::JClassLoader;
use jni::strings::JNIStr;
use jni::sys::jclass;
use jni::{Env, JavaVM, NativeMethod};
use std::ffi::c_void;
use std::sync::OnceLock;

const SCHEDULER_BYTES: &[u8] =
    include_bytes!("../../build/hooks/dev/crussty/hooks/SchedulerHooks.class");
const STORAGE_BYTES: &[u8] = include_bytes!("../../build/hooks/dev/crusty/hooks/StorageHooks.class");
const NET_BYTES: &[u8] = include_bytes!("../../build/hooks/dev/crussty/hooks/NetHooks.class");
const TICK_BYTES: &[u8] = include_bytes!("../../build/hooks/dev/crussty/hooks/TickHook.class");

static INSTALLED: OnceLock<Result<(), String>> = OnceLock::new();

// --- SchedulerHooks natives (wired 1:1 onto the scheduler brick) ----------

unsafe extern "C" fn n_on_tick(_env: *mut jni::sys::JNIEnv, _class: jclass) {
    let _ = scheduler::on_tick_boundary();
}

unsafe extern "C" fn n_on_level_tick(_env: *mut jni::sys::JNIEnv, _class: jclass) {
    scheduler::on_level_tick();
}

unsafe extern "C" fn n_on_task_scheduled(_env: *mut jni::sys::JNIEnv, _class: jclass) {
    let _ = scheduler::on_task_scheduled();
}

unsafe extern "C" fn n_on_block_ticks(_env: *mut jni::sys::JNIEnv, _class: jclass) {
    let _ = scheduler::on_block_ticks();
}

// --- NetHooks / TickHook natives (probes carry no data; no-op for now) -----

unsafe extern "C" fn n_noop(_env: *mut jni::sys::JNIEnv, _class: jclass) {}

/// Define one hook class into the system class loader and register its
/// natives. `env` must be attached and pinned for the whole call.
fn define_and_register(
    env: &mut Env,
    name: &JNIStr,
    bytes: &[u8],
    natives: &[(&JNIStr, &JNIStr, *const c_void)],
) -> Result<(), jni::errors::Error> {
    let loader = JClassLoader::get_system_class_loader(env)?;
    let class = env.define_class(Some(name), &loader, bytes)?;

    let methods = natives
        .iter()
        .map(|(m, sig, fp)| {
            // SAFETY: `fp` is a function pointer whose ABI matches `sig`
            // (every candidate in this file is a static `(jclass, ...)` fn).
            unsafe { NativeMethod::from_raw_parts(m, sig, *fp as *mut c_void) }
        })
        .collect::<Vec<_>>();
    // SAFETY: same pointer list as the map above; every entry matches its
    // Java declaration (see hook-src/).
    unsafe { env.register_native_methods(class, &methods) }
}

/// Define and wire the hook classes, once. Must run on an attached thread
/// (agent init runs inside `JNI_CreateJavaVM` where `AttachCurrentThread` is
/// a fault) — hence [`schedule_install`].
fn install_once() -> Result<(), String> {
    INSTALLED
        .get_or_init(|| {
            let vm_ptr = *crate::VM
                .get()
                .ok_or_else(|| "JavaVM not captured yet".to_string())?;
            let vm = unsafe { JavaVM::from_raw(vm_ptr as *mut jni::sys::JavaVM) };
            // The attach hands us a JNIEnv; E (the callback error type) is
            // jni::Error, which satisifes `E: From<Error>`.
            let installed: Result<(), jni::errors::Error> = vm
                .attach_current_thread(|env| -> Result<(), jni::errors::Error> {
                define_and_register(
                    env,
                    jni::jni_str!("dev/crussty/hooks/SchedulerHooks"),
                    SCHEDULER_BYTES,
                    &[
                        (jni::jni_str!("onTick"), jni::jni_str!("()V"), n_on_tick as *const c_void),
                        (jni::jni_str!("onLevelTick"), jni::jni_str!("()V"), n_on_level_tick as *const c_void),
                        (jni::jni_str!("onTaskScheduled"), jni::jni_str!("()V"), n_on_task_scheduled as *const c_void),
                        (jni::jni_str!("onBlockTicks"), jni::jni_str!("()V"), n_on_block_ticks as *const c_void),
                    ],
                )?;
                // StorageHooks: the storage brick already exports the JNI
                // natives; reuse its pointers (a `V`-less mix of ()Z/()V/
                // array signatures — all static, all match the Java decls).
                define_and_register(
                    env,
                    jni::jni_str!("dev/crusty/hooks/StorageHooks"),
                    STORAGE_BYTES,
                    &[
                        (
                            jni::jni_str!("nStorageActive"), jni::jni_str!("()Z"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nStorageActive
                                as *const c_void,
                        ),
                        (
                            jni::jni_str!("nBeginSave"), jni::jni_str!("()Z"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nBeginSave as *const c_void,
                        ),
                        (
                            jni::jni_str!("nEndSave"), jni::jni_str!("()Z"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nEndSave as *const c_void,
                        ),
                        (
                            jni::jni_str!("nChunkWritten"), jni::jni_str!("()V"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nChunkWritten
                                as *const c_void,
                        ),
                        (
                            jni::jni_str!("nMarkAutosave"), jni::jni_str!("()V"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nMarkAutosave
                                as *const c_void,
                        ),
                        (
                            jni::jni_str!("nReadChunk"), jni::jni_str!("(IIII)[B"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nReadChunk
                                as *const c_void,
                        ),
                        (
                            jni::jni_str!("nWriteChunk"), jni::jni_str!("(IIII[B)Z"),
                            storage::Java_dev_crusty_hooks_StorageHooks_nWriteChunk
                                as *const c_void,
                        ),
                    ],
                )?;
                define_and_register(
                    env,
                    jni::jni_str!("dev/crussty/hooks/NetHooks"),
                    NET_BYTES,
                    &[
                        (jni::jni_str!("onDecode"), jni::jni_str!("()V"), n_noop as *const c_void),
                        (jni::jni_str!("onEncode"), jni::jni_str!("()V"), n_noop as *const c_void),
                        (jni::jni_str!("onIntention"), jni::jni_str!("()V"), n_noop as *const c_void),
                        (jni::jni_str!("onProtocolSwap"), jni::jni_str!("()V"), n_noop as *const c_void),
                        (jni::jni_str!("onChannelInactive"), jni::jni_str!("()V"), n_noop as *const c_void),
                    ],
                )?;
                define_and_register(
                    env,
                    jni::jni_str!("dev/crussty/hooks/TickHook"),
                    TICK_BYTES,
                    &[(jni::jni_str!("onEntry"), jni::jni_str!("()V"), n_noop as *const c_void)],
                )?;
                Ok(())
            });
            installed.map_err(|e| format!("attach+install hooks: {e:?}"))?;
            Ok(())
        })
        .clone()
}

/// Install the hook classes after the VM is fully created and this thread is
/// genuinely attached — `AttachCurrentThread` from inside `JNI_CreateJavaVM`
/// (agent init) SIGSEGVs the JVM (thread not yet attachable). Kernel classes
/// (and tick boundaries, where the probes run) load many seconds later.
pub fn schedule_install() {
    std::thread::Builder::new()
        .name("crussty-hook-install".into())
        .spawn(|| {
            std::thread::sleep(std::time::Duration::from_secs(2));
            // Voice the outcome either way: a failed install leaves patched
            // kernel classes with NoClassDefFoundError on first execution.
            match install_once() {
                Ok(()) => eprintln!(
                    "[crussty-runtime] transform hook classes installed (4)"
                ),
                Err(e) => eprintln!(
                    "[crussty-runtime] !!! transform hook classes NOT installed: {e} \
                     (patched kernel classes will fail with NoClassDefFoundError)"
                ),
            }
        })
        .expect("spawn hook install thread");
}