//! Runtime method-name aliases for the transform engine.
//!
//! Rules are written in Mojang (official) names. Paper 1.20.5+ and NeoForge run
//! official names at runtime and match by name; Forge 1.20.1 runs **Searge**
//! names, where `MinecraftServer.tickServer` is `m_5705_`. Without this table
//! such rules matched the class, matched no method, produced an empty plan and
//! the whole platform surface (tick boundary, save hooks, network codecs)
//! silently stayed unwired — the bug this file exists to kill.
//!
//! The table is generated, never hand-edited:
//!
//! ```text
//! python3 scripts/gen_srg_aliases.py \
//!     <mcp_config>/srg_to_official_<mc>.tsrg > runtime/src/platform/runtime_names.rs
//! ```
//!
//! `Rule::new` consults [`aliases`] for every rule, so platform bricks *and*
//! modules get the translation for free. A rule whose target does not exist in
//! the mapped version simply has no alias and falls back to the engine's
//! descriptor matching.
// GENERATED by scripts/gen_srg_aliases.py — do not edit by hand.
//
// Forge 1.20.1 runtime (Searge) names for the methods the default rule
// tables target. Source: ForgeGradle mcp_config srg_to_official_1.20.1.tsrg.
pub const SRG_ALIASES: &[(&str, &str, &str, &str)] = &[
    ("net/minecraft/server/MinecraftServer", "tickServer", "(Ljava/util/function/BooleanSupplier;)V", "m_5705_"),
    ("net/minecraft/server/MinecraftServer", "saveAllChunks", "(ZZZ)Z", "m_129885_"),
    ("net/minecraft/server/level/ServerLevel", "tick", "(Ljava/util/function/BooleanSupplier;)V", "m_8793_"),
    ("net/minecraft/world/ticks/LevelTicks", "tick", "(JILjava/util/function/BiConsumer;)V", "m_193225_"),
    ("net/minecraft/network/PacketDecoder", "decode", "(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V", "decode"),
    ("net/minecraft/network/PacketEncoder", "encode", "(Lio/netty/channel/ChannelHandlerContext;Lnet/minecraft/network/protocol/Packet;Lio/netty/buffer/ByteBuf;)V", "encode"),
    ("net/minecraft/server/network/ServerHandshakePacketListenerImpl", "handleIntention", "(Lnet/minecraft/network/protocol/handshake/ClientIntentionPacket;)V", "m_7322_"),
    ("net/minecraft/network/Connection", "channelInactive", "(Lio/netty/channel/ChannelHandlerContext;)V", "channelInactive"),
];

/// Alias names for `class.method(descriptor)`, empty when the runtime name is
/// already the official one (Paper/NeoForge) or the target is unknown here.
pub fn aliases(class: &str, method: &str, descriptor: &str) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    for (c, m, d, srg) in SRG_ALIASES {
        // A rule may declare `descriptor = "*"` (match every overload of the
        // named method); then every mapped overload of that name contributes
        // an alias instead of exactly one.
        let desc_ok = descriptor == "*" || *d == descriptor;
        if *c == class && *m == method && desc_ok && *srg != *m && !out.contains(srg) {
            out.push(srg);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tick_rule_has_the_1_20_1_srg_alias() {
        let a = aliases(
            "net/minecraft/server/MinecraftServer",
            "tickServer",
            "(Ljava/util/function/BooleanSupplier;)V",
        );
        assert_eq!(a, vec!["m_5705_"], "Forge 1.20.1 tick entry alias");
    }

    #[test]
    fn wildcard_descriptor_collects_every_overload() {
        let a = aliases("net/minecraft/world/ticks/LevelTicks", "tick", "*");
        assert_eq!(a, vec!["m_193225_"], "LevelTicks.tick (JILjava/util/function/BiConsumer;)V");
    }

    #[test]
    fn unmapped_target_has_no_alias() {
        assert!(aliases("a/b/C", "d", "()V").is_empty());
    }

    #[test]
    fn netty_overrides_are_not_duplicated() {
        // decode/encode/channelInactive keep their names under SRG: aliasing
        // them to themselves would only pay a compare per class load.
        assert!(aliases(
            "net/minecraft/network/PacketDecoder",
            "decode",
            "(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V"
        )
        .is_empty());
    }
}
