[book]
title = "Crussty Platform"
authors = ["PLANETA9091"]
language = "en"
description = "Crussty — native Rust plugin platform for Paper-family Minecraft kernels"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/PLANETA9091/CRUSSTY"
edit-url-template = "https://github.com/PLANETA9091/CRUSSTY/edit/master/book/{path}"
additional-css = ["css/oled.css"]
additional-js = ["js/ascii.js"]


[output.html.search]
enable = true
limit-results = 30
